# Generated by Django 4.1 on 2022-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_order_shippingprice_alter_order_taxprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
