# Generated by Django 4.1 on 2022-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_order_totalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/Product.jpg", null=True, upload_to=""
            ),
        ),
    ]
