# Generated by Django 4.1 on 2022-12-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
